apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-app-deployment
  namespace: angular-dotnet-crud
spec:
  replicas: 1 
    matchLabels:
      app: angular-app
  template:
    metadata:
      labels:
        app: angular-app
    spec:
      containers:
      - name: app-container
        image: raptoverdad/angular-dotnet-crud-front:master
        imagePullPolicy: Always
        ports:
        - containerPort: 80

          # Agrega más variables de entorno según tus necesidades