apiVersion: v1
kind: Service
metadata:
  name: angular-app-service
  namespace: angular-dotnet-crud
spec:
  selector:
    app: angular-app  # Esto debe coincidir con la etiqueta de tu Deployment
  ports:
    - protocol: TCP
      port: 80  # Puerto externo del Service
      targetPort: 80  # Puerto del contenedor que deseas exponer
  type: LoadBalancer  # Tipo de Service, puedes ajustarlo según tus necesidades