apiVersion: v1
kind: Service
metadata:
  name: mysql-db
  namespace: angular-dotnet-crud
spec:
  selector:
    app: angular-dotnet-crud-database
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: LoadBalancer