apiVersion: v1
kind: Service
metadata:
  name: angular-aspdotnet-crud-webapi
  namespace: angular-dotnet-crud
spec:
  selector:
    app: dotnet-webapi
  ports:
    - protocol: TCP
      port: 80  # Puerto externo del LoadBalancer
      targetPort: 80  # Puerto del servicio interno
  type: LoadBalancer