on: push
name: deploy

jobs:
  build-and-push:
    name: build and push image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - image: raptoverdad/angular-dotnet-crud-front
            dockerfile: angular-application/Dockerfile
            context: ./angular-application
          - image: raptoverdad/angular-dotnet-crud-back
            dockerfile: ASPNET-MYSQL/Dockerfile
            context: ./ASPNET-MYSQL
          - image: raptoverdad/angular-dotnet-crud-database
            dockerfile: ASPNET-MYSQL/database-config/Dockerfile
            context: ./ASPNET-MYSQL/database-config
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ matrix.image }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Configure AWS 
        run: aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY }} && aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} && aws configure set default.region ${{ secrets.AWS_REGION }}
      - name: Update Kubeconfig
        run: aws eks update-kubeconfig --name BABC-CLUSTER --region sa-east-1

      - name: Deploy vue app deployment to eks
        run: kubectl apply -f kubernetes/angular-app-deployment.yml -n angular-dotnet-crud
      - name: Deploy vue app service to eks
        run: kubectl apply -f kubernetes/angular-app-service.yml -n angular-dotnet-crud
      - name: Deploy express api deployment to eks
        run: kubectl apply -f kubernetes/dotnet-api-deployment.yml -n angular-dotnet-crud
      - name: Deploy express api service to eks
        run: kubectl apply -f kubernetes/dotnet-api-service.yml -n angular-dotnet-crud
      - name: Deploy database deployment to eks
        run: kubectl apply -f kubernetes/database-deployment.yml -n angular-dotnet-crud
      - name: Deploy database service to eks
        run: kubectl apply -f kubernetes/database-service.yml -n angular-dotnet-crud

